import json
import logging
import os
from enum import StrEnum
from types import SimpleNamespace

from static_gallery.metadata import DERIVED_FIELDS, Metadata, read_metadata

logger = logging.getLogger(__name__)


class NodeType(StrEnum):
    HOME = "HOME"
    DIRECTORY = "DIRECTORY"
    PAGE = "PAGE"
    GALLERY = "GALLERY"
    IMAGE = "IMAGE"
    STATIC = "STATIC"


class Node:
    def __init__(self, path, parent=None, type=None):
        if isinstance(path, os.DirEntry):
            # Ideally, path is a DirEntry object generated by os.scandir(),
            # which gives us everything we need.
            self.path = path.path
            self.name = path.name
            self.ctime = path.stat().st_ctime
            self.mtime = path.stat().st_mtime
            self._is_dir = path.is_dir(follow_symlinks=False)
        else:
            # But we also support a path string, mostly to boot strap the
            # scanning process with the intial source path.
            self.path = os.path.abspath(path)
            self.name = self.path.split(os.sep)[-1]
            self.ctime = os.stat(self.path).st_ctime
            self.mtime = os.stat(self.path).st_mtime
            self._is_dir = os.path.isdir(self.path)

        # Files have suffixes, but directories don't.
        if self._is_dir:
            self.stem = self.name
            self.suffix = ""
        else:
            self.stem, self.suffix = os.path.splitext(self.name)

        self.type = type
        self.parent = parent

        # For containers and page bundles, path to an index file
        # (index.md, index.html, or index.htm) if one exists.
        # Starts as None until the directory is scanned.
        self.index_path = None

        # For IMAGE nodes, path to a paired markdown file (same stem).
        self.content_path = None

        self.dirs = []
        self.pages = []
        self.images = []
        self.assets = []
        self._metadata = None

    def get_content_path(self):
        path = None
        if self.type == NodeType.PAGE:
            path = self.index_path if self.index_path else self.path
        elif self.type == NodeType.IMAGE:
            path = self.content_path
        elif self.type in (NodeType.DIRECTORY, NodeType.GALLERY, NodeType.HOME):
            path = self.index_path
        return path

    def add_child(self, node):
        match node.type:
            case NodeType.PAGE:
                self.pages.append(node)
            case NodeType.IMAGE:
                self.images.append(node)
            case NodeType.STATIC:
                self.assets.append(node)
            case NodeType.DIRECTORY | NodeType.GALLERY:
                self.dirs.append(node)
            case _:
                raise ValueError(f"Unknown node type: '{node.type}'.")
        return node.type

    @property
    def metadata(self):
        if self.type != NodeType.IMAGE:
            return Metadata()
        if self._metadata is None:
            try:
                self._metadata = read_metadata(self.path)
            except Exception:
                logger.warning(
                    "Failed to read metadata from %s", self.path, exc_info=True
                )
                self._metadata = Metadata()
        return self._metadata

    @property
    def template_name(self):
        if self.type == NodeType.HOME:
            return "home.html"
        if self.type == NodeType.PAGE:
            return "page.html"
        if self.type == NodeType.IMAGE:
            return "image.html"
        if self.type == NodeType.GALLERY:
            return "gallery.html"
        if self.type == NodeType.DIRECTORY:
            return "directory.html"
        return "default.html"

    @property
    def title_fallback(self):
        if self.type in (NodeType.PAGE, NodeType.IMAGE):
            return self.stem
        return self.name

    def is_image(self):
        suffixes = [".jpg", ".jpeg", ".webp", ".png", ".gif"]
        if self.suffix.lower() in suffixes:
            return True
        return False

    def is_markdown(self):
        suffixes = [".md", ".markdown"]
        if self.suffix.lower() in suffixes:
            return True
        return False

    def is_html(self):
        suffixes = [".html", ".htm"]
        if self.suffix.lower() in suffixes:
            return True
        return False

    def is_dir(self):
        return self._is_dir

    def is_gallery(self):
        return (
            len(self.images) > 0
            and len(self.pages) == 0
            and len(self.assets) == 0
            and len(self.dirs) == 0
            and self.index_path is None
        )

    def to_dict(self):
        data = {}
        data["type"] = self.type
        data["path"] = self.path
        data["stem"] = self.stem
        data["suffix"] = self.suffix
        data["mtime"] = self.mtime
        if self.index_path:
            data["index_path"] = self.index_path
        if self.content_path:
            data["content_path"] = self.content_path
        if self.parent:
            data["parent"] = self.parent.path
        if len(self.pages):
            data["pages"] = [item.to_dict() for item in self.pages]
        if len(self.images):
            data["images"] = [item.to_dict() for item in self.images]
        if len(self.assets):
            data["assets"] = [item.to_dict() for item in self.assets]
        if len(self.dirs):
            data["dirs"] = [item.to_dict() for item in self.dirs]
        return data

    def __str__(self):
        return json.dumps(self.to_dict(), indent=4)


def build_image_data(img):
    m = img.metadata
    data = SimpleNamespace(
        name=img.name,
        id=img.stem,
        url=img.stem + "/",
        src=img.stem + "/" + img.name,
        metadata=m,
    )
    for attr in DERIVED_FIELDS:
        setattr(data, attr, getattr(m, attr))
    return data
