import json
import os


class StaticNode:
    def __init__(self, path, parent=None, type=None):
        if isinstance(path, os.DirEntry):
            # Ideally, path is a DirEntry object generated by os.scandir(),
            # which gives us everything we need.
            self.path = path.path
            self.name = path.name
            self.ctime = path.stat().st_ctime
            self.mtime = path.stat().st_mtime
            self._is_dir = path.is_dir(follow_symlinks=False)
        else:
            # But we also support a path string, mostly to boot strap the
            # scanning process with the intial source path.
            self.path = os.path.abspath(path)
            self.name = self.path.split(os.sep)[-1]
            self.ctime = os.stat(self.path).st_ctime
            self.mtime = os.stat(self.path).st_mtime
            self._is_dir = os.path.isdir(self.path)

        # Files have suffixes, but directories don't.
        if self._is_dir:
            self.stem = self.name
            self.suffix = ""
        else:
            self.stem, self.suffix = os.path.splitext(self.name)

        self.type = type
        self.parent = parent

        # For containers, if there's an index file, that's the text content
        # of the container. It starts as None until the directory is scanned.
        self.text = None

        self.dirs = []
        self.pages = []
        self.images = []
        self.assets = []

    def get_markdown_path(self):
        path = None
        if self.type == "MARKDOWN":
            path = self.path
        elif self.type in ["DIRECTORY", "GALLERY", "HOME"]:
            path = self.text
        return path

    def add_child(self, node):
        match node.type:
            case "MARKDOWN":
                self.pages.append(node)
            case "IMAGE":
                self.images.append(node)
            case "STATIC":
                self.assets.append(node)
            case "DIRECTORY" | "GALLERY":
                self.dirs.append(node)
            case _:
                raise ValueError(f"Unknown node type: '{node.type}'.")
        return node.type

    def is_image(self):
        suffixes = [".jpg", ".jpeg", ".webp", ".png", ".gif"]
        if self.suffix.lower() in suffixes:
            return True
        return False

    def is_markdown(self):
        suffixes = [".md", ".markdown"]
        if self.suffix.lower() in suffixes:
            return True
        return False

    def is_dir(self):
        return self._is_dir

    def is_gallery(self):
        return len(self.images) > 0 and len(self.pages) == 0

    def to_dict(self):
        data = {}
        data["type"] = self.type
        data["path"] = self.path
        data["stem"] = self.stem
        data["suffix"] = self.suffix
        data["mtime"] = self.mtime
        if self.text:
            data["text"] = self.text
        if self.parent:
            data["parent"] = self.parent.path
        if len(self.pages):
            data["pages"] = [item.to_dict() for item in self.pages]
        if len(self.images):
            data["images"] = [item.to_dict() for item in self.images]
        if len(self.assets):
            data["assets"] = [item.to_dict() for item in self.assets]
        if len(self.dirs):
            data["dirs"] = [item.to_dict() for item in self.dirs]
        return data

    def __str__(self):
        return json.dumps(self.to_dict(), indent=4)
